export const projects = [
  {
    id: 1,
    reverse: false,
    name: "News",
    img: require("./images/News_screenshot.png").default,
    technologies: "React, Styled-components, External API",
    desc: "Compared to other news site, users can read countless articles on latest world events, sport, business, technology, and culture without navigating noisy interfaces. The application uses Guardian and Weather API.",
    link: "https://optimistic-chandrasekhar-bb37ab.netlify.app/",
    link_git: "https://github.com/Saxofounix/news_lite",
  },
  {
    id: 2,
    reverse: true,
    name: "User Auth",
    img: require("./images/login_screenshot.png").default,
    technologies: "Node, Express, Passport.js, Mongoose, EJS, Bootstrap",
    desc: "User authentication application, connected to MongoDB, using passport's local strategy middleware, EJS' templating engine, bcrypt package for hashing passwords, and flash for displaying messages. ",
    link: "https://user-auth-app-heroku.herokuapp.com/",
    link_git: "https://github.com/Saxofounix/auth",
  },
  {
    id: 3,
    reverse: false,
    name: "Recipes",
    technologies: "React, Styled-components, External API",
    img: require("./images/recipes_screenshot.png").default,

    desc: "React application that allows users to search for recipes based on a given ingredient. Two API endpoints are fetched to serve the client with not only the recipes, but also video tutorials. ",
    link: "https://naughty-bhaskara-21472f.netlify.app",
    link_git: "https://github.com/Saxofounix/ingredients",
  },
  {
    id: 4,
    reverse: true,
    name: "One pager",
    img: require("./images/spa_screenshot.png").default,
    technologies: "React, Styled-components",
    desc: "One page website built in React utilizing styled-components, react-router-dom with smooth scroll and SVGs. Components were reused and conditionally rendered to increase the sites' performance.",
    link: "https://jolly-pare-ad155a.netlify.app/",
    link_git: "https://jolly-pare-ad155a.netlify.app/",
  },
  {
    id: 5,
    reverse: false,
    name: "This portfolio",
    img: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=820&q=80",
    technologies: "React, Styled-components",
    desc: "This site was built with React, react-router and styled-components. ",
    link_git: "https://github.com/Saxofounix/react-portfolio",
  },
];
